repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "23.7.0"
    hooks:
      - id: black-jupyter

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.282"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
